package features.rewards;

public enum Reward {

SOUND_007, SOUND_AIRHORN, SOUND_AMONGUS, SOUND_AXEL_F, SOUND_AYE_AYE_CAPTAIN, SOUND_BADUM_TS, SOUND_BRAUSE_JACKPOT, SOUND_BRAWL, SOUND_CANTINA_BAND, SOUND_CHALLENGE, SOUND_CHIPPININ, SOUND_CRAZY_FROG, SOUND_CTN_UUH, SOUND_ELDEN_RING, SOUND_ENORM, SOUND_FAIL, SOUND_FANFARE, SOUND_FOX_INTRO, SOUND_GOLDEN_JACKPOT, SOUND_HES_A_PIRATE, SOUND_INCEPTION, SOUND_INTRO_CLIP, SOUND_JACKPOT, SOUND_JOJO_GOLDEN_WIND, SOUND_JOJO_STROHEIM, SOUND_JOJO_TBC, SOUND_LAUGHING, SOUND_MAGIC, SOUND_NANI, SOUND_NICE, SOUND_OH_YEAH, SOUND_OK_LETS_GO, SOUND_OOF, SOUND_SACKGESICHT, SOUND_SKRILLEX, SOUND_SON_OF_A_BITCH, SOUND_SOVIET, SOUND_SPOILER, SOUND_STRANGER_THINGS, SOUND_SUPER_JACKPOT, SOUND_THOMAS_EARRAPE, SOUND_WASTED, SOUND_WILD_WEST, SOUND_WILHELM_SCREAM, SOUND_X_FILES,
ACTION_HUNT_CHALLENGE, ACTION_IRL_CHALLENGE, ACTION_RANDOM_SOUND, ACTION_RANDOM_SPORT,
COMMAND_TTS, COMMAND_TTS_LEGACY, COMMAND_TTS_REROLL, COMMAND_SLOTS

}
