########################################################################################
#                                                                                      #
#  _____        _ _       _       ___    ___   _____ _           _   _           _     #
# |_   _|      (_) |     | |     /   |  |_  | /   \ |         | | | |         | |    #
#   | |_      ___| |_ ___| |  / /| |    | | | /  \/ |    _| |_| |   ___ | |_   #
#   | \ \ /\ / / | / | '_ \/ /_| |    | | | |   | '_ \ / _` | | '_ \ / _ \| |  #
#   | |\ V  V /| | || (| | | \___  |/\__/ / | \__/\ | | | (_| | |_| |_) | (_) | |_   #
#   \_/ \_/\_/ |_|\__\___|_| |_|   |_/\____/   \____/_| |_|\__,_|\__|_./ \___/ \|  #
#                                                                                      #
#                                                                                      #
########################################################################################

debug: true
bot:
    # Name of your bot
    name: "CaptainsSupport"

    # Current version of your bot
    version: "0.1"

# Application - API Settings
api:
    # Twitch Application Client Id
    twitch_client_id: 6r1x3u1sh0lgfqbpjus4cn4k35s5il

    # Twitch Application Client Secret
    twitch_client_secret: 8inphfrhvspk61e4535guwqobjqlz6

# Credentials
credentials:
    # OAuth Token for IRC USer (You can get yours here: http://twitchapps.com/tmi/)
    irc: oauth:cuvvzyb01yd5b10r1facp9pcq9n47u

# Channels - The bot will connect to all listed channels
channels:
    - CaptainCasimir